# Copyright (c) Picogrid, Inc.
# SPDX-License-Identifier: MPL-2.0

"""Private, replaceable adapter for the intentionally narrow public wire contract."""

from .codec import (
    decode_entity_json,
    decode_entity_payload,
    decode_entity_protobuf,
    decode_location_json,
    decode_location_payload,
    decode_location_protobuf,
    encode_entity_json,
    encode_entity_payload,
    encode_entity_protobuf,
    encode_location_json,
    encode_location_payload,
    encode_location_protobuf,
    extract_entity_identity,
)
from .json_codec import decode_json, decode_model_json, encode_json
from .topics import (
    ENTITY_JSON_SUBSCRIPTION,
    ENTITY_PROTOBUF_SUBSCRIPTION,
    LOCATION_JSON_SUBSCRIPTION,
    LOCATION_PROTOBUF_SUBSCRIPTION,
    EntityTopic,
    LocationTopic,
    ParsedTopic,
    TaskTopic,
    TopicFamily,
    build_entity_protobuf_topic,
    build_entity_subscription_filters,
    build_entity_topic,
    build_location_protobuf_topic,
    build_location_subscription_filters,
    build_location_topic,
    build_task_request_topic,
    build_task_response_topic,
    parse_entity_topic,
    parse_location_topic,
    parse_protocol_topic,
    parse_task_topic,
    validate_publish_topic,
    validate_subscription_filter,
)

__all__ = [
    "ENTITY_JSON_SUBSCRIPTION",
    "ENTITY_PROTOBUF_SUBSCRIPTION",
    "LOCATION_JSON_SUBSCRIPTION",
    "LOCATION_PROTOBUF_SUBSCRIPTION",
    "EntityTopic",
    "LocationTopic",
    "ParsedTopic",
    "TaskTopic",
    "TopicFamily",
    "build_entity_protobuf_topic",
    "build_entity_subscription_filters",
    "build_entity_topic",
    "build_location_protobuf_topic",
    "build_location_subscription_filters",
    "build_location_topic",
    "build_task_request_topic",
    "build_task_response_topic",
    "decode_entity_json",
    "decode_entity_payload",
    "decode_entity_protobuf",
    "decode_json",
    "decode_location_json",
    "decode_location_payload",
    "decode_location_protobuf",
    "decode_model_json",
    "encode_entity_json",
    "encode_entity_payload",
    "encode_entity_protobuf",
    "encode_json",
    "encode_location_json",
    "encode_location_payload",
    "encode_location_protobuf",
    "extract_entity_identity",
    "parse_entity_topic",
    "parse_location_topic",
    "parse_protocol_topic",
    "parse_task_topic",
    "validate_publish_topic",
    "validate_subscription_filter",
]
