# Copyright (c) Picogrid, Inc.
# SPDX-License-Identifier: MPL-2.0

"""Generate the manifest-controlled Python API reference."""

from __future__ import annotations

import argparse
import ast
import contextlib
import importlib
import json
import math
import operator
import re
import shutil
import sys
import tempfile
import types
from collections import Counter
from collections.abc import Callable, Iterable, Iterator, Mapping, Sequence
from dataclasses import dataclass
from enum import Enum
from pathlib import Path
from typing import Any, cast, get_args, get_origin

import griffe
from pydantic import BaseModel
from pydantic_core import PydanticUndefined

_GENERATED_BANNER = (
    "<!-- Generated by scripts/generate_api_reference.py. DO NOT EDIT. "
    "Regenerate with make generate-reference. -->"
)
_PLACEHOLDER = re.compile(r"\b(?:TODO|TBD)\b|(?:^|\s)\.\.\.\s*$", re.IGNORECASE)
_REPOSITORY_ROOT = Path(__file__).resolve().parents[1]
_DEFAULT_MANIFEST = _REPOSITORY_ROOT / "scripts" / "public-api-manifest.json"
_DEFAULT_PACKAGE_ROOT = _REPOSITORY_ROOT / "src"
_DEFAULT_DOCS_ROOT = _REPOSITORY_ROOT / "docs" / "reference" / "python"
_MISSING = "—"
_GROUP_SUMMARIES = {
    "client": "Client lifecycle, readiness, and preflight.",
    "clock": "ECN-relative clock measurement and tolerance checks.",
    "configuration": "Explicit configuration, credentials, and TLS.",
    "entities": "Typed entity publication and observation.",
    "locations": "Location observation and PLI publication.",
    "tasks": "Typed task registration and dispatch.",
    "streams": "Bounded async event delivery.",
    "diagnostics": "Connection status, preflight, and receipts.",
    "protobuf": "Bounded protobuf decoding helpers.",
    "exceptions": "Public error hierarchy and codes.",
    "testing": "Offline mock ECN test surface.",
    "workflows": "Reusable reviewed workflows shared by examples and notebooks.",
}
_RST_ROLE = re.compile(r":(?:meth|class|func):`([^`]+)`")


def _site_route(route: str) -> str:
    """Build a mount-neutral, root-absolute site route.

    The documentation mount (Astro ``base``) is deployment configuration; the
    build-time link rewriter in ``docs/astro.config.mjs`` prefixes the configured
    base, so generated content never embeds it.
    """
    cleaned = route.strip("/")
    if not cleaned:
        return "/"
    return f"/{cleaned}/"


@dataclass(frozen=True)
class ReferenceBuild:
    """A deterministic in-memory reference build."""

    pages: dict[str, str]
    inventory: dict[str, Any]
    symbols: dict[str, Any]
    field_descriptions: dict[str, dict[str, str]]
    approved_members: dict[str, tuple[str, ...]]
    source_references: dict[str, dict[str, int]]


def _load_json(path: Path) -> dict[str, Any]:
    value = json.loads(path.read_text())
    if not isinstance(value, dict):
        raise ValueError(f"expected a JSON object in {path}")
    return cast(dict[str, Any], value)


def _static_package(package_root: Path, package: str) -> Any:
    return griffe.load(
        package,
        search_paths=[package_root],
        docstring_parser="google",
        allow_inspection=False,
        force_inspection=False,
        resolve_aliases=False,
    )


def _in_package(module_name: str, package: str) -> bool:
    return module_name == package or module_name.startswith(f"{package}.")


@contextlib.contextmanager
def _runtime_modules(
    package_root: Path, package: str
) -> Iterator[tuple[types.ModuleType, types.ModuleType, types.ModuleType]]:
    """Import the documented package from one search root, then restore state.

    Documentation extraction must read the exact package under ``package_root``
    even when another copy is already imported, but it must not leave the
    interpreter's module table rebound for anything running afterwards.
    """

    root = package_root.resolve()
    owned = {name: module for name, module in sys.modules.items() if _in_package(name, package)}
    loaded = sys.modules.get(package)
    loaded_file = Path(cast(str, getattr(loaded, "__file__", ""))).resolve() if loaded else None
    if loaded_file is not None and root not in loaded_file.parents:
        for name in owned:
            del sys.modules[name]
    sys.path.insert(0, str(root))
    try:
        public = importlib.import_module(package)
        testing = importlib.import_module(f"{package}.testing")
        workflows = importlib.import_module(f"{package}.workflows")
        for module in (public, testing, workflows):
            resolved = Path(cast(str, getattr(module, "__file__", ""))).resolve()
            if root not in resolved.parents:
                raise RuntimeError(
                    f"{module.__name__} resolved outside the requested package root; "
                    "refusing to mix source-tree and installed-package metadata"
                )
        yield public, testing, workflows
    finally:
        sys.path.remove(str(root))
        for name in [name for name in sys.modules if _in_package(name, package)]:
            del sys.modules[name]
        sys.modules.update(owned)


def _all_symbols(manifest: Mapping[str, Any]) -> list[dict[str, Any]]:
    return [
        *cast(list[dict[str, Any]], manifest["symbols"]),
        *cast(list[dict[str, Any]], manifest["testing_symbols"]),
        *cast(list[dict[str, Any]], manifest["workflow_symbols"]),
    ]


def _static_object(package: Any, module: str, name: str, package_name: str) -> Any:
    relative = module.removeprefix(f"{package_name}.")
    return package.modules_collection[f"{package_name}.{relative}.{name}"]


def _runtime_object(
    symbol: Mapping[str, Any],
    public: types.ModuleType,
    testing: types.ModuleType,
    workflows: types.ModuleType,
) -> object:
    module = str(symbol["module"])
    if module.startswith(f"{public.__name__}.testing"):
        namespace = testing
    elif module.startswith(f"{public.__name__}.workflows"):
        namespace = workflows
    else:
        namespace = public
    return getattr(namespace, str(symbol["name"]))


def _clean_doc_text(value: object) -> str:
    text = _RST_ROLE.sub(r"`\1`", str(value).strip())
    return re.sub(r"``([^`]+)``", r"`\1`", text)


def _summary(obj: Any) -> str:
    docstring = getattr(obj, "docstring", None)
    value = _clean_doc_text(getattr(docstring, "value", ""))
    if not value:
        return ""
    return value.split("\n\n", 1)[0].replace("\n", " ").strip()


def _description_sections(obj: Any) -> list[Any]:
    docstring = getattr(obj, "docstring", None)
    return list(getattr(docstring, "parsed", ()))


def _doc_parts(
    obj: Any,
) -> tuple[
    dict[str, str],
    list[tuple[str, str]],
    list[tuple[str, str]],
    list[tuple[str, str]],
]:
    parameters: dict[str, str] = {}
    returns: list[tuple[str, str]] = []
    yields: list[tuple[str, str]] = []
    raises: list[tuple[str, str]] = []
    for section in _description_sections(obj):
        section_name = type(section).__name__
        values = getattr(section, "value", ())
        if not isinstance(values, list):
            continue
        if section_name == "DocstringSectionParameters":
            for item in values:
                parameters[str(item.name)] = _clean_doc_text(item.description)
        elif section_name in {"DocstringSectionReturns", "DocstringSectionYields"}:
            target = returns if section_name.endswith("Returns") else yields
            descriptions = " ".join(_clean_doc_text(item.description) for item in values)
            annotations = [_expression_text(getattr(item, "annotation", None)) for item in values]
            annotation = next((item for item in annotations if item), _MISSING)
            target.append((annotation, descriptions))
        elif section_name == "DocstringSectionRaises":
            for item in values:
                raises.append(
                    (
                        _expression_text(getattr(item, "annotation", None)),
                        _clean_doc_text(item.description),
                    )
                )
    return parameters, returns, yields, raises


def _doc_attributes(obj: Any) -> dict[str, str]:
    attributes: dict[str, str] = {}
    for section in _description_sections(obj):
        if type(section).__name__ != "DocstringSectionAttributes":
            continue
        values = getattr(section, "value", ())
        if not isinstance(values, list):
            continue
        for item in values:
            attributes[str(item.name)] = _clean_doc_text(item.description)
    return attributes


def _expression_text(value: object) -> str:
    if value is None:
        return ""
    text = str(value)
    return text.replace("typing.", "").replace("collections.abc.", "")


# Substitution only rewrites unqualified names, since a qualified private
# name has no module-local value to resolve. Detection is deliberately
# broader: it must also catch qualified and digit-prefixed identifiers.
# Detection stays lexical: any private identifier reaching page text is a leak.
_ANY_PRIVATE_NAME = re.compile(r"(?<![\w])_\w+")
# A quoted value rendered in a signature or a table cell is data, not a symbol
# a reader could import, so a default such as `'_TOKEN'` is not a leak. Only
# whitespace-free spans qualify, so an ambiguous span stays scanned rather than
# silently exempted.
_QUOTED_LITERAL = re.compile(r"'[^'\s]*'|\"[^\"\s]*\"")
# In a signature only a default expression is data; the same quoted text in
# annotation position is a forward reference to a type the reader can look up.
_DEFAULT_LITERAL = re.compile(r"(=\s*)('[^'\s]*'|\"[^\"\s]*\")")
# Header labels for the table columns that render a value rather than prose.
# An enum table ends in `Value`, so its final column is data, unlike the
# `Description` column every other table ends with.
_VALUE_COLUMNS = frozenset({"Default", "Value"})
# `_table` escapes prose pipes, so only unescaped pipes delimit cells.
_CELL_BOUNDARY = re.compile(r"(?<!\\)\|")
# Source references the generator itself emitted. Only these are exempt, so a
# private name inside a docstring-authored link is still reported.
_EMITTED_SOURCE_REFERENCES: list[str] = []
# Protocol methods the reference documents. Approved manifest symbols and
# members are added per build, so a documented dunder export such as
# `__version__` is not mistaken for private surface.
_PROTOCOL_MAGIC_NAMES = frozenset(
    {
        "__init__",
        "__call__",
        "__enter__",
        "__exit__",
        "__aenter__",
        "__aexit__",
        "__iter__",
        "__next__",
        "__aiter__",
        "__anext__",
        "__await__",
        "__len__",
        "__getitem__",
        "__contains__",
    }
)
# The manifest's documented version attribute, rendered on the index page.
_VERSION_ATTRIBUTE = "__version__"
# The only underscore-prefixed names a generated page may name.
_ALLOWED_UNDERSCORE = frozenset({*_PROTOCOL_MAGIC_NAMES, _VERSION_ATTRIBUTE})


# Bounds `**` so a source constant cannot make generation hang.
_MAX_EXPONENT = 64
# Bounds every intermediate result, not just one operation.
_MAX_RESULT_BITS = 256
_ALLOWED_BINOPS: dict[type[ast.operator], Callable[[Any, Any], Any]] = {
    ast.Add: operator.add,
    ast.Sub: operator.sub,
    ast.Mult: operator.mul,
    ast.Div: operator.truediv,
    ast.FloorDiv: operator.floordiv,
    ast.Mod: operator.mod,
    ast.Pow: operator.pow,
}


def _static_literal(node: ast.expr) -> object:
    """Evaluate a constant expression from source, or raise for anything else.

    Resolution reads the candidate source rather than a live module, so a
    process that imported and mutated the package cannot change what the
    generated pages say. Only literals and arithmetic between numbers are
    accepted; a name, call, or attribute reference raises.
    """

    if isinstance(node, ast.Constant):
        if isinstance(node.value, float) and not math.isfinite(node.value):
            raise ValueError("non-finite literal")
        if isinstance(node.value, int) and not isinstance(node.value, bool):
            if node.value.bit_length() > _MAX_RESULT_BITS:
                # Rendering a huge literal can trip Python's int-to-str limit.
                raise ValueError("integer literal out of range")
            return node.value
        if node.value is None or isinstance(node.value, (str, bytes, bool, float)):
            return node.value
        raise ValueError("unsupported constant")
    if isinstance(node, ast.UnaryOp) and isinstance(node.op, (ast.UAdd, ast.USub)):
        operand = _static_literal(node.operand)
        if not isinstance(operand, (int, float)) or isinstance(operand, bool):
            raise ValueError("unsupported unary operand")
        return +operand if isinstance(node.op, ast.UAdd) else -operand
    if isinstance(node, ast.BinOp) and type(node.op) in _ALLOWED_BINOPS:
        left, right = _static_literal(node.left), _static_literal(node.right)
        if not all(isinstance(v, (int, float)) and not isinstance(v, bool) for v in (left, right)):
            raise ValueError("unsupported operands")
        if isinstance(node.op, ast.Pow) and (
            not isinstance(right, int) or abs(right) > _MAX_EXPONENT
        ):
            # An unbounded integer exponent can consume arbitrary time and memory.
            raise ValueError("exponent out of range")
        result = _ALLOWED_BINOPS[type(node.op)](left, right)
        if isinstance(result, float) and not math.isfinite(result):
            raise ValueError("non-finite result")
        if isinstance(result, int) and result.bit_length() > _MAX_RESULT_BITS:
            # Bounds cumulative growth: nested powers each pass the exponent
            # check while the intermediate value explodes.
            raise ValueError("result out of range")
        return result
    if isinstance(node, (ast.Tuple, ast.List)):
        items = [_static_literal(item) for item in node.elts]
        return tuple(items) if isinstance(node, ast.Tuple) else items
    raise ValueError("unsupported expression")


def _resolve_private_defaults(function: Any) -> None:
    """Replace private identifier defaults with their values, in place.

    Only a default that is exactly one private identifier is resolved. That
    names a module constant the reader cannot import, and the value is what the
    reader actually needs. Any other expression is left untouched, so a string
    literal that merely looks private cannot be rewritten into invalid syntax.
    """

    module = getattr(function, "module", None)
    if module is None:
        return
    for parameter in getattr(function, "parameters", ()):
        default = parameter.default
        if not isinstance(default, griffe.ExprName):
            continue
        name = str(default.name)
        if not name.startswith("_") or name.startswith("__"):
            continue
        try:
            attribute = module[name]
        except (KeyError, TypeError):
            continue
        source = getattr(attribute, "value", None)
        if source is None:
            continue
        # Anything this cannot evaluate stays unresolved, which is fail-closed:
        # the private name remains visible for the private-surface check.
        try:
            value = _static_literal(ast.parse(str(source), mode="eval").body)
        except (SyntaxError, ValueError, TypeError, ZeroDivisionError, OverflowError):
            continue
        parameter.default = _default_text(value)


def _type_text(annotation: object) -> str:
    if annotation is None or annotation is type(None):
        return "None"
    if annotation is Ellipsis:
        return "..."
    if isinstance(annotation, str):
        return annotation
    origin = get_origin(annotation)
    if origin is types.UnionType:
        return " | ".join(_type_text(item) for item in get_args(annotation))
    if origin is not None:
        args = get_args(annotation)
        origin_name = getattr(origin, "__name__", str(origin).replace("typing.", ""))
        if origin_name == "Union":
            return " | ".join(_type_text(item) for item in args)
        if origin_name == "Literal":
            return f"Literal[{', '.join(_default_text(item) for item in args)}]"
        if origin_name == "Annotated":
            return _type_text(args[0])
        return f"{origin_name}[{', '.join(_type_text(item) for item in args)}]"
    return str(getattr(annotation, "__name__", annotation)).replace("typing.", "")


def _default_text(value: object) -> str:
    if value is PydanticUndefined:
        return _MISSING
    if isinstance(value, Enum):
        return f"{type(value).__name__}.{value.name}"
    if isinstance(value, str):
        return repr(value)
    if isinstance(value, (bool, int, float)) or value is None:
        return repr(value)
    if isinstance(value, (list, tuple)):
        left, right = ("[", "]") if isinstance(value, list) else ("(", ")")
        rendered = ", ".join(_default_text(item) for item in value)
        if isinstance(value, tuple) and len(value) == 1:
            # (x) is a parenthesized scalar; a one-element tuple needs the comma.
            rendered += ","
        return left + rendered + right
    if isinstance(value, dict):
        pairs = sorted(value.items(), key=lambda item: repr(item[0]))
        return "{" + ", ".join(f"{_default_text(k)}: {_default_text(v)}" for k, v in pairs) + "}"
    return repr(value).replace("typing.", "")


def _annotation_metadata(annotation: object) -> list[object]:
    origin = get_origin(annotation)
    if origin is None:
        return []
    args = get_args(annotation)
    origin_name = getattr(origin, "__name__", str(origin).replace("typing.", ""))
    if origin_name == "Annotated":
        metadata = list(args[1:])
        for item in args[1:]:
            metadata.extend(cast(Sequence[object], getattr(item, "metadata", ())))
        return [*metadata, *_annotation_metadata(args[0])]
    return [nested for argument in args for nested in _annotation_metadata(argument)]


def _constraint_items(metadata: Sequence[object]) -> list[str]:
    keys = (
        "gt",
        "ge",
        "lt",
        "le",
        "multiple_of",
        "min_length",
        "max_length",
        "pattern",
        "max_digits",
        "decimal_places",
        "strict",
    )
    constraints: list[str] = []
    for item in metadata:
        for key in keys:
            value = getattr(item, key, None)
            if value is not None:
                constraints.append(f"{key}={_default_text(value)}")
        if getattr(item, "allow_inf_nan", None) is False:
            constraints.append("finite")
    return list(dict.fromkeys(constraints))


def _model_fields(model: type[BaseModel]) -> list[dict[str, Any]]:
    fields: list[dict[str, Any]] = []
    for name, field in model.model_fields.items():
        if field.default_factory is not None:
            factory_name = getattr(field.default_factory, "__name__", "factory")
            default_text = f"{factory_name}()"
        else:
            default_text = _default_text(field.default)
        fields.append(
            {
                "name": name,
                "type": _type_text(field.annotation),
                "required": field.is_required(),
                "default": default_text,
                "constraints": _constraint_items(
                    [*field.metadata, *_annotation_metadata(field.annotation)]
                ),
                "description": _clean_doc_text(field.description or ""),
            }
        )
    return fields


def _signatures(obj: Any) -> list[str]:
    """Render callable signatures as valid Python declarations."""

    raw_overloads = getattr(obj, "overloads", ())
    overloads = list(raw_overloads) if isinstance(raw_overloads, list) else []
    functions = overloads or ([obj] if callable(getattr(obj, "signature", None)) else [])
    for function in functions:
        _resolve_private_defaults(function)
    return [
        f"{'async def ' if 'async' in function.labels else 'def '}{function.signature()}"
        for function in functions
    ]


def _member_signatures(member: Any) -> list[str]:
    signatures = _signatures(member)
    if signatures:
        return signatures
    annotation = _expression_text(getattr(member, "annotation", None))
    return [f"{member.name}: {annotation}"] if annotation else [str(member.name)]


def _source_path(obj: Any, package_root: Path) -> str:
    filepath = Path(str(obj.filepath)).resolve()
    try:
        relative = filepath.relative_to(package_root.resolve())
    except ValueError:
        module_path = str(obj.module.path).replace(".", "/")
        relative = Path(f"{module_path}.py")
    return (Path("src") / relative).as_posix()


def _source_link(
    obj: Any,
    package_root: Path,
    version: str,
    source_link_template: str,
) -> str:
    return (
        source_link_template.format(
            project_version=version,
            repository_path=_source_path(obj, package_root),
        )
        + f"#L{obj.lineno}"
    )


def _source_reference(
    obj: Any,
    package_root: Path,
    version: str,
    source_link_template: str,
) -> str:
    path = _source_path(obj, package_root)
    package_prefix = "src/picogrid_ecn_client/"
    label = path.removeprefix(package_prefix) if path.startswith(package_prefix) else ""
    title = f"Source · {label}" if label else "Source"
    reference = f"[{title}]({_source_link(obj, package_root, version, source_link_template)})"
    _EMITTED_SOURCE_REFERENCES.append(reference)
    return reference


def _format_signature(signature: str) -> str:
    if len(signature) <= 96 or "(" not in signature:
        return signature
    prefix, remainder = signature.split("(", 1)
    parameters, suffix = remainder.rsplit(")", 1)
    parts = _split_parameters(parameters)
    return f"{prefix}(\n" + "".join(f"    {part},\n" for part in parts) + f"){suffix}"


def _split_parameters(parameters: str) -> list[str]:
    parts: list[str] = []
    start = 0
    depth = 0
    quote = ""
    for index, character in enumerate(parameters):
        if quote:
            # Inside a literal, only the matching unescaped quote ends it, so a
            # comma in a string default cannot split one parameter into two.
            preceding = len(parameters[:index]) - len(parameters[:index].rstrip("\\"))
            if character == quote and preceding % 2 == 0:
                # An even run of backslashes escapes itself, so the quote closes.
                quote = ""
            continue
        if character in "\"'":
            quote = character
        elif character in "[({":
            depth += 1
        elif character in "])}":
            depth -= 1
        elif character == "," and depth == 0:
            parts.append(parameters[start:index].strip())
            start = index + 1
    final = parameters[start:].strip()
    if final:
        parts.append(final)
    return parts


def _frontmatter(title: str, description: str, order: int, *, toc: bool) -> str:
    lines = [
        "---",
        f"title: {json.dumps(title, ensure_ascii=False)}",
        f"description: {json.dumps(description, ensure_ascii=False)}",
        f"sidebar: {{ order: {order} }}",
        f"tableOfContents: {str(toc).lower()}",
        "---",
    ]
    return "\n".join(lines)


def _guidance_note(
    group: Mapping[str, Any],
    version: str,
    example_paths: Sequence[str] | None = None,
    *,
    name_group: bool = True,
) -> str:
    guides = ", ".join(
        f"[{route}]({_site_route(route)})" for route in cast(list[str], group["related_guides"])
    )
    paths = (
        cast(Sequence[str], group["related_examples"]) if example_paths is None else example_paths
    )
    examples = ", ".join(
        f"[{path.removeprefix('examples/')}]"
        f"(https://github.com/picogrid/ecn-sdk-python/blob/v{version}/{path})"
        for path in paths
    )
    related = f"> Related guidance: {guides}.\n>\n> Runnable examples: {examples}."
    if not name_group:
        # The group index is the page a leaf points at; linking it to itself
        # adds no navigation and makes the index read like a leaf.
        return related
    # Leaf pages are no longer listed in the sidebar, so each one names the
    # group it belongs to and links to that group's index, which inventories it.
    group_title = cast(str, group["title"])
    group_route = cast(str, group["route"])
    return (
        f"> Part of [{group_title}]({_site_route(group_route)})"
        f" in the Python API reference.\n>\n{related}"
    )


def _table(headers: Sequence[str], rows: Iterable[Sequence[str]]) -> str:
    rendered = [f"| {' | '.join(headers)} |", f"| {' | '.join('---' for _ in headers)} |"]
    for row in rows:
        rendered.append(
            "| " + " | ".join(value.replace("|", "\\|").replace("\n", " ") for value in row) + " |"
        )
    return "\n".join(rendered)


def _inline_code(value: str) -> str:
    longest_run = max((len(run) for run in re.findall(r"`+", value)), default=0)
    delimiter = "`" * (longest_run + 1)
    padding = " " if value.startswith(("`", " ")) or value.endswith(("`", " ")) else ""
    return f"{delimiter}{padding}{value}{padding}{delimiter}"


def _signature_block(signatures: Sequence[str]) -> str:
    return "\n\n".join(
        f"```python\n{_format_signature(signature)}\n```" for signature in signatures
    )


def _overloads(obj: Any) -> list[Any]:
    raw = getattr(obj, "overloads", ())
    return list(raw) if isinstance(raw, list) else []


def _is_literal_narrowed(overloads: Sequence[Any], name: str) -> bool:
    """Report whether overloads split one parameter across ``Literal`` variants."""

    annotations: list[str] = []
    for overload in overloads:
        for parameter in getattr(overload, "parameters", ()):
            if str(parameter.name) == name:
                annotations.append(_expression_text(parameter.annotation) or "")
    distinct = set(annotations)
    return len(distinct) > 1 and any(item.startswith("Literal[") for item in distinct)


def _overload_return_type(obj: Any) -> str:
    overloads = _overloads(obj)
    literal_overloads = [
        overload
        for overload in overloads
        if any(
            "Literal[" in _expression_text(parameter.annotation)
            for parameter in getattr(overload, "parameters", ())
        )
    ]
    candidates = literal_overloads or overloads
    rendered: list[str] = []
    generic_bases: set[str] = set()
    for overload in candidates:
        annotation = _expression_text(getattr(overload, "returns", None))
        generic_base = annotation.partition("[")[0] if "[" in annotation else ""
        if generic_base and generic_base in generic_bases:
            continue
        if annotation and annotation not in rendered:
            rendered.append(annotation)
            if generic_base:
                generic_bases.add(generic_base)
    return " | ".join(rendered)


def _callable_sections(obj: Any, *, heading_level: int) -> str:
    _resolve_private_defaults(obj)
    parameters, returns, yields, raises = _doc_parts(obj)
    chunks: list[str] = []
    implementation_parameters = {
        str(parameter.name): parameter for parameter in getattr(obj, "parameters", ())
    }
    overloads = _overloads(obj)
    public_parameters = (
        list(getattr(overloads[0], "parameters", ()))
        if overloads
        else list(implementation_parameters.values())
    )
    rows = []
    for parameter in public_parameters:
        if parameter.name in {"self", "cls", "/", "*"}:
            continue
        implementation = implementation_parameters[str(parameter.name)]
        default = _expression_text(implementation.default) or _MISSING
        # Overload sets sometimes narrow one parameter to a distinct Literal per
        # variant (the task mode). The table describes the parameter as a whole,
        # so fall back to the implementation annotation in exactly that case;
        # every other parameter keeps its public overload annotation.
        annotation = parameter.annotation
        if overloads and _is_literal_narrowed(overloads, str(parameter.name)):
            annotation = implementation.annotation
        rows.append(
            (
                str(parameter.name),
                _expression_text(annotation) or _MISSING,
                default,
                parameters.get(str(parameter.name), ""),
            )
        )
    overload_return = _overload_return_type(obj)
    if overload_return and returns:
        returns = [(overload_return, returns[0][1])]
    heading = "#" * heading_level
    if rows:
        chunks.extend(
            (f"{heading} Parameters", _table(("Name", "Type", "Default", "Description"), rows))
        )
    if returns:
        chunks.extend((f"{heading} Returns", _table(("Type", "Description"), returns)))
    if yields:
        chunks.extend((f"{heading} Yields", _table(("Type", "Description"), yields)))
    if raises:
        chunks.extend((f"{heading} Raises", _table(("Exception", "Description"), raises)))
    return "\n\n".join(chunks)


def _member_section(
    member: Any,
    package_root: Path,
    version: str,
    source_link_template: str,
) -> str:
    chunks = [f"## `{member.name}`", _summary(member)]
    signatures = _member_signatures(member)
    if signatures:
        chunks.append(_signature_block(signatures))
    callable_sections = _callable_sections(member, heading_level=3)
    if callable_sections:
        chunks.append(callable_sections)
    chunks.append(_source_reference(member, package_root, version, source_link_template))
    return "\n\n".join(chunk for chunk in chunks if chunk)


def _exception_hierarchy(exception: type[BaseException]) -> str:
    names: list[str] = []
    for base in exception.__mro__:
        if base.__name__ in {"object", "Exception", "BaseException"}:
            continue
        names.append(base.__name__)
        if base.__name__ == "ECNClientError":
            break
    return " → ".join(reversed(names))


def _class_declaration(obj: Any, name: str) -> str:
    bases = [rendered for base in getattr(obj, "bases", ()) if (rendered := _expression_text(base))]
    suffix = f"({', '.join(bases)})" if bases else ""
    return f"class {name}{suffix}: ..."


def _public_attributes(obj: Any) -> list[tuple[str, str, str]]:
    descriptions = _doc_attributes(obj)
    return [
        (
            str(name),
            _expression_text(getattr(member, "annotation", None)) or _MISSING,
            descriptions.get(str(name), ""),
        )
        for name, member in getattr(obj, "members", {}).items()
        if not str(name).startswith("_") and type(member).__name__ == "Attribute"
    ]


def _render_symbol_page(
    route_symbols: Sequence[dict[str, Any]],
    static_symbols: Mapping[str, Any],
    runtime_symbols: Mapping[str, object],
    fields: Mapping[str, list[dict[str, Any]]],
    groups: Mapping[str, dict[str, Any]],
    workflow_examples: Mapping[str, Sequence[str]],
    package_root: Path,
    version: str,
    source_link_template: str,
    order: int,
) -> str:
    primary = route_symbols[0]
    kind = str(primary["kind"])
    title = str(primary["name"]) if len(route_symbols) == 1 else "Synthetic tokens"
    canonical = f"{primary['module']}.{primary['name']}"
    static = static_symbols[canonical]
    summary = _summary(static) or f"API reference for {title}."
    attributes = (
        _public_attributes(static)
        if kind == "class"
        and str(primary["name"]).endswith("Result")
        and ".workflows." in str(primary["module"])
        else []
    )
    toc = (
        len(route_symbols) > 1
        or kind in {"pydantic-model", "enum", "type-alias", "callback-alias"}
        or bool(primary.get("members"))
        or bool(attributes)
    )
    imports = []
    for symbol in route_symbols:
        module = str(symbol["module"])
        package = module.split(".", 1)[0]
        if module.startswith(f"{package}.testing"):
            namespace = f"{package}.testing"
        elif module.startswith(f"{package}.workflows"):
            namespace = f"{package}.workflows"
        else:
            namespace = package
        imports.append(f"```python\nfrom {namespace} import {symbol['name']}\n```")
    chunks = [
        _frontmatter(title, summary, order, toc=toc),
        _GENERATED_BANNER,
        _guidance_note(
            groups[str(primary["group"])],
            version,
            workflow_examples.get(canonical)
            or (
                cast(Sequence[str], primary["related_examples"])
                if "related_examples" in primary
                else None
            ),
        ),
        *imports,
        summary,
    ]
    for symbol in route_symbols:
        name = str(symbol["name"])
        symbol_canonical = f"{symbol['module']}.{name}"
        obj = static_symbols[symbol_canonical]
        runtime = runtime_symbols[symbol_canonical]
        symbol_kind = str(symbol["kind"])
        class_level_source = symbol_kind in {
            "pydantic-model",
            "enum",
            "exception",
            "class",
            "protocol",
        }
        if len(route_symbols) > 1:
            chunks.extend((f"## `{name}`", _summary(obj), f"```python\n{name}: str\n```"))
        elif symbol_kind == "pydantic-model":
            model_fields = fields[symbol_canonical]
            model_parameters = [
                f"{field['name']}: {field['type']}"
                + ("" if field["required"] else f" = {field['default']}")
                for field in model_fields
            ]
            chunks.append(_signature_block([f"{name}(*, {', '.join(model_parameters)})"]))
            chunks.append(_source_reference(obj, package_root, version, source_link_template))
            chunks.extend(
                (
                    "## Fields",
                    _table(
                        ("Name", "Type", "Required", "Default", "Constraints", "Description"),
                        (
                            (
                                str(field["name"]),
                                str(field["type"]),
                                "yes" if field["required"] else "no",
                                str(field["default"]),
                                ", ".join(
                                    _inline_code(item)
                                    for item in cast(list[str], field["constraints"])
                                )
                                or _MISSING,
                                str(field["description"]),
                            )
                            for field in model_fields
                        ),
                    ),
                )
            )
        elif symbol_kind == "enum":
            enum_type = cast(type[Enum], runtime)
            chunks.extend(
                (
                    f"```python\nclass {name}(Enum): ...\n```",
                    _source_reference(obj, package_root, version, source_link_template),
                    "## Members",
                    _table(
                        ("Name", "Value"),
                        ((member.name, _default_text(member.value)) for member in enum_type),
                    ),
                )
            )
        elif symbol_kind in {"type-alias", "callback-alias"}:
            chunks.extend(
                ("## Aliased form", f"```python\n{name} = {_expression_text(obj.value)}\n```")
            )
        elif symbol_kind == "constant":
            pass
        elif symbol_kind == "exception":
            hierarchy = _exception_hierarchy(cast(type[BaseException], runtime))
            direct_base = hierarchy.split(" → ")[-2] if name != "ECNClientError" else "Exception"
            chunks.extend(
                (
                    f"```python\nclass {name}({direct_base}): ...\n```",
                    _source_reference(obj, package_root, version, source_link_template),
                    f"**Hierarchy:** `{hierarchy}`",
                )
            )
        elif symbol_kind in {"class", "protocol"}:
            chunks.extend(
                (
                    f"```python\n{_class_declaration(obj, name)}\n```",
                    _source_reference(obj, package_root, version, source_link_template),
                )
            )
            public_attributes = (
                _public_attributes(obj)
                if name.endswith("Result") and ".workflows." in str(symbol["module"])
                else []
            )
            if public_attributes:
                chunks.extend(
                    (
                        "## Attributes",
                        _table(
                            ("Name", "Type", "Description"),
                            public_attributes,
                        ),
                    )
                )
        else:
            chunks.append(_signature_block(_signatures(obj)))
            details = _callable_sections(obj, heading_level=2)
            if details:
                chunks.append(details)
        if symbol.get("async_context_manager"):
            chunks.append(f"Use `{name}` with `async with` to manage its asynchronous lifecycle.")
        if symbol.get("async_iterator"):
            chunks.append(
                f"Consume `{name}` with `async for` and close it asynchronously when needed."
            )
        for member_name in cast(list[str], symbol.get("members", [])):
            member = obj.get_member(member_name)
            if member is not None:
                chunks.append(_member_section(member, package_root, version, source_link_template))
        if not class_level_source:
            chunks.append(_source_reference(obj, package_root, version, source_link_template))
    return "\n\n".join(chunk for chunk in chunks if chunk).rstrip() + "\n"


def _render_group_index(
    group: Mapping[str, Any],
    symbols: Sequence[dict[str, Any]],
    summaries: Mapping[str, str],
    order: int,
    version: str,
) -> str:
    group_summary = _GROUP_SUMMARIES[str(group["id"])]
    chunks = [
        _frontmatter(str(group["title"]), group_summary, order, toc=False),
        _GENERATED_BANNER,
        _guidance_note(group, version, name_group=False),
    ]
    rows: list[tuple[str, str]] = []
    seen_routes: set[str] = set()
    for symbol in symbols:
        route = str(symbol["route"])
        if route in seen_routes:
            continue
        seen_routes.add(route)
        canonical = f"{symbol['module']}.{symbol['name']}"
        rows.append((f"[`{symbol['name']}`]({_site_route(route)})", summaries[canonical]))
    chunks.append(_table(("Symbol", "Summary"), rows))
    return "\n\n".join(chunks).rstrip() + "\n"


def _render_root_index(groups: Sequence[dict[str, Any]], version: str, order: int) -> str:
    chunks = [
        _frontmatter(
            "Python API reference",
            "Manifest-controlled Python API reference.",
            order,
            toc=True,
        ),
        _GENERATED_BANNER,
        "Use this reference with the linked workflow and security guidance on each API page.",
        "## Groups",
        _table(
            ("Group", "Description"),
            (
                (
                    f"[{group['title']}]({_site_route(str(group['route']))})",
                    _GROUP_SUMMARIES[str(group["id"])],
                )
                for group in groups
            ),
        ),
        f"## `{_VERSION_ATTRIBUTE}`",
        f"```python\nfrom picogrid_ecn_client import {_VERSION_ATTRIBUTE}\n```",
        f"```python\n{_VERSION_ATTRIBUTE} = {version!r}\n```",
        "The installed package version.",
    ]
    return "\n\n".join(chunks).rstrip() + "\n"


def build_reference(
    *,
    manifest_path: Path = _DEFAULT_MANIFEST,
    package_root: Path = _DEFAULT_PACKAGE_ROOT,
    repository_root: Path = _REPOSITORY_ROOT,
) -> ReferenceBuild:
    """Build all pages and the normalized inventory in memory.

    The documented package is imported only for the duration of extraction so
    callers that already imported it (tests, other tooling) keep their modules.
    """

    manifest = _load_json(manifest_path)
    package_name = str(manifest["package"])
    package = _static_package(package_root, package_name)
    with _runtime_modules(package_root, package_name) as (public, testing, workflows):
        return _compose_reference(
            manifest=manifest,
            package=package,
            package_name=package_name,
            package_root=package_root,
            repository_root=repository_root,
            public=public,
            testing=testing,
            workflows=workflows,
        )


def _workflow_examples(
    repository_root: Path,
    package_root: Path,
    symbols: Sequence[Mapping[str, Any]],
) -> dict[str, tuple[str, ...]]:
    manifest = _load_json(repository_root / "examples" / "manifest.json")
    documented_by_module: dict[str, dict[str, str]] = {}
    for symbol in symbols:
        module = str(symbol["module"])
        name = str(symbol["name"])
        documented_by_module.setdefault(module, {})[name] = f"{module}.{name}"

    references: dict[str, set[str]] = {}
    examples: dict[str, list[str]] = {}
    for example in cast(list[dict[str, Any]], manifest["examples"]):
        workflow = example.get("workflow")
        if not isinstance(workflow, Mapping):
            continue
        module = str(workflow["module"])
        function = str(workflow["function"])
        canonical = f"{module}.{function}"
        if canonical not in references:
            module_path = package_root.joinpath(*module.split(".")).with_suffix(".py")
            if not module_path.is_file():
                module_path = module_path.with_suffix("") / "__init__.py"
            tree = ast.parse(module_path.read_text(), filename=str(module_path))
            definitions = {
                node.name: node
                for node in tree.body
                if isinstance(node, (ast.AsyncFunctionDef, ast.FunctionDef))
            }
            definition = definitions.get(function)
            if definition is None:
                raise ValueError(f"workflow {canonical} is not defined in {module_path}")
            # Follow module-private helpers transitively. A workflow that delegates model
            # construction to a helper still documents that model, so a refactor that moves
            # the call must not silently drop the example link.
            referenced_names: set[str] = set()
            pending = [definition]
            visited = {function}
            while pending:
                node_names = {
                    node.id if isinstance(node, ast.Name) else node.attr
                    for node in ast.walk(pending.pop())
                    if isinstance(node, ast.Name | ast.Attribute)
                }
                referenced_names |= node_names
                for name in sorted(node_names):
                    helper = definitions.get(name)
                    if helper is not None and name.startswith("_") and name not in visited:
                        visited.add(name)
                        pending.append(helper)
            references[canonical] = {
                documented_by_module[module][name]
                for name in referenced_names
                if name in documented_by_module.get(module, {})
            }
        path = str(example["source_path"])
        for referenced in (canonical, *sorted(references[canonical])):
            paths = examples.setdefault(referenced, [])
            if path not in paths:
                paths.append(path)
    return {canonical: tuple(paths) for canonical, paths in examples.items()}


def _compose_reference(
    *,
    manifest: Mapping[str, Any],
    package: Any,
    package_name: str,
    package_root: Path,
    repository_root: Path,
    public: types.ModuleType,
    testing: types.ModuleType,
    workflows: types.ModuleType,
) -> ReferenceBuild:
    version = str(
        _load_json(repository_root / "scripts" / "release-policy.json")["project_version"]
    )
    source_link_template = str(cast(Mapping[str, Any], manifest["source_link"])["template"])
    symbols = _all_symbols(manifest)
    groups = cast(list[dict[str, Any]], manifest["groups"])
    groups_by_id = {str(group["id"]): group for group in groups}
    workflow_examples = _workflow_examples(repository_root, package_root, symbols)
    static_symbols: dict[str, Any] = {}
    runtime_symbols: dict[str, object] = {}
    model_fields: dict[str, list[dict[str, Any]]] = {}
    descriptions: dict[str, dict[str, str]] = {}
    members: dict[str, tuple[str, ...]] = {}
    inventory_symbols: list[dict[str, Any]] = []
    source_paths: list[str] = []
    summaries: dict[str, str] = {}
    for symbol in symbols:
        canonical = f"{symbol['module']}.{symbol['name']}"
        obj = _static_object(package, str(symbol["module"]), str(symbol["name"]), package_name)
        runtime = _runtime_object(symbol, public, testing, workflows)
        static_symbols[canonical] = obj
        runtime_symbols[canonical] = runtime
        summaries[canonical] = _summary(obj)
        approved = tuple(cast(list[str], symbol.get("members", [])))
        members[canonical] = approved
        member_inventory = []
        for member_name in approved:
            member = obj.get_member(member_name)
            member_inventory.append(
                {
                    "name": member_name,
                    "signatures": _member_signatures(member) if member is not None else [],
                }
            )
        entry: dict[str, Any] = {
            "name": symbol["name"],
            "kind": symbol["kind"],
            "canonical_import": (
                f"{package_name}.testing.{symbol['name']}"
                if str(symbol["module"]).startswith(f"{package_name}.testing")
                else (
                    f"{package_name}.workflows.{symbol['name']}"
                    if str(symbol["module"]).startswith(f"{package_name}.workflows")
                    else f"{package_name}.{symbol['name']}"
                )
            ),
            "source_path": _source_path(obj, package_root),
            "signatures": _signatures(obj),
            "members": member_inventory,
            "model_fields": [],
            "enum_members": [],
            "alias_target": None,
        }
        if symbol["kind"] == "pydantic-model":
            extracted = _model_fields(cast(type[BaseModel], runtime))
            model_fields[canonical] = extracted
            descriptions[canonical] = {
                str(field["name"]): str(field["description"]) for field in extracted
            }
            entry["model_fields"] = extracted
        elif (
            symbol["kind"] == "class"
            and str(symbol["name"]).endswith("Result")
            and str(symbol["module"]).startswith(f"{package_name}.workflows")
        ):
            descriptions[canonical] = {
                name: description for name, _, description in _public_attributes(obj)
            }
        elif symbol["kind"] == "enum":
            entry["enum_members"] = [
                {"name": item.name, "value": _default_text(item.value)}
                for item in cast(type[Enum], runtime)
            ]
        elif symbol["kind"] in {"type-alias", "callback-alias"}:
            entry["alias_target"] = _expression_text(obj.value)
        inventory_symbols.append(entry)
        if entry["source_path"] not in source_paths:
            source_paths.append(cast(str, entry["source_path"]))
    pages: dict[str, str] = {"reference/python": _render_root_index(groups, version, 0)}
    for group_order, group in enumerate(groups, start=1):
        grouped = [symbol for symbol in symbols if symbol["group"] == group["id"]]
        pages[str(group["route"])] = _render_group_index(
            group, grouped, summaries, group_order, version
        )
    routes: dict[str, list[dict[str, Any]]] = {}
    for symbol in symbols:
        routes.setdefault(str(symbol["route"]), []).append(symbol)
    emitted: dict[str, Counter[str]] = {}
    for symbol_order, route in enumerate(routes, start=1):
        _EMITTED_SOURCE_REFERENCES.clear()
        pages[route] = _render_symbol_page(
            routes[route],
            static_symbols,
            runtime_symbols,
            model_fields,
            groups_by_id,
            workflow_examples,
            package_root,
            version,
            source_link_template,
            symbol_order,
        )
        # Snapshot what this page actually emitted, so an exemption is spent
        # once per emission rather than matching every identical line.
        emitted[route] = Counter(_EMITTED_SOURCE_REFERENCES)
    inventory: dict[str, Any] = {
        "manifest_version": manifest["manifest_version"],
        "package": package_name,
        "source_paths": source_paths,
        "symbols": inventory_symbols,
    }
    source_references = {route: dict(counts) for route, counts in emitted.items()}
    return ReferenceBuild(
        pages, inventory, static_symbols, descriptions, members, source_references
    )


def private_surface_errors(build: ReferenceBuild) -> list[str]:
    """Return the private identifiers rendered into generated pages.

    A generated page must never name a symbol the reader cannot import. Source
    links and the generated-file banner legitimately carry private module paths,
    so only rendered body text is inspected.
    """

    # Manifest approval cannot launder a private name: only public identifiers
    # are added, so approving a member such as `_secret` still fails the check.
    documented = {*_PROTOCOL_MAGIC_NAMES, _VERSION_ATTRIBUTE}
    for canonical in build.symbols:
        documented.add(canonical.rsplit(".", 1)[-1])
    for members in build.approved_members.values():
        documented.update(members)
    # Only recognized protocol methods may be exempted, so listing an arbitrary
    # dunder such as `__secret__` as a member cannot hide it from this scan.
    approved_underscore = {
        member
        for members in build.approved_members.values()
        for member in members
        if member in _PROTOCOL_MAGIC_NAMES
    }
    documented = {
        name
        for name in documented
        if not name.startswith("_") or name in _ALLOWED_UNDERSCORE or name in approved_underscore
    }

    errors: list[str] = []
    for route, page in sorted(build.pages.items()):
        # Each emission grants exactly one exemption, so a docstring that
        # reproduces its own page's source line is still scanned.
        remaining = dict(build.source_references.get(route, {}))
        in_code_block = False
        value_columns: set[int] | None = None
        for number, line in enumerate(page.splitlines(), start=1):
            if line.startswith("```"):
                in_code_block = not in_code_block
                continue
            if not line.startswith("|"):
                value_columns = None
            if line == _GENERATED_BANNER:
                continue
            if remaining.get(line):
                remaining[line] -= 1
                continue
            # Quoted text is data only where the generator renders a value: a
            # default expression in a signature, or a table's value column.
            # A quoted annotation such as `value: "_PrivateModel"` is a type
            # reference, and every table's trailing column is docstring prose,
            # so both stay scanned.
            if in_code_block:
                scanned = _DEFAULT_LITERAL.sub(r"\1''", line)
            elif line.startswith("|"):
                cells = _CELL_BOUNDARY.split(line)
                if value_columns is None:
                    value_columns = {
                        index for index, cell in enumerate(cells) if cell.strip() in _VALUE_COLUMNS
                    }
                scanned = "|".join(
                    _QUOTED_LITERAL.sub("''", cell) if index in value_columns else cell
                    for index, cell in enumerate(cells)
                )
            else:
                scanned = line
            for name in sorted(set(_ANY_PRIVATE_NAME.findall(scanned))):
                if name in documented:
                    continue
                errors.append(f"{route}:{number}: private symbol {name} rendered into the page")
    return errors


def docstring_completeness_errors(build: ReferenceBuild) -> list[str]:
    """Return exact names for missing or placeholder summaries and field descriptions."""
    errors: list[str] = []
    for canonical, obj in build.symbols.items():
        summary = _summary(obj)
        if not summary:
            errors.append(f"{canonical}: missing docstring summary")
        elif _PLACEHOLDER.search(summary):
            errors.append(f"{canonical}: placeholder docstring summary")
        # Class objects expose their constructor signature, but interface pages
        # render a bare declaration rather than a constructor table, so only
        # standalone functions are checked here; members are checked below.
        if type(obj).__name__ == "Function":
            for undocumented in _undocumented_parameters(obj):
                errors.append(f"{canonical}({undocumented}): missing parameter description")
        for member_name in build.approved_members[canonical]:
            member = obj.get_member(member_name)
            member_summary = _summary(member) if member is not None else ""
            member_path = f"{canonical}.{member_name}"
            if not member_summary:
                errors.append(f"{member_path}: missing docstring summary")
            elif _PLACEHOLDER.search(member_summary):
                errors.append(f"{member_path}: placeholder docstring summary")
            if member is not None:
                for undocumented in _undocumented_parameters(member):
                    errors.append(f"{member_path}({undocumented}): missing parameter description")
        for field_name, description in build.field_descriptions.get(canonical, {}).items():
            field_path = f"{canonical}.{field_name}"
            if not description:
                errors.append(f"{field_path}: missing Field description")
            elif _PLACEHOLDER.search(description):
                errors.append(f"{field_path}: placeholder Field description")
    return errors


def _route_path(route: str) -> Path:
    relative = route.removeprefix("reference/python").strip("/")
    if not relative:
        return Path("index.md")
    if "/" not in relative:
        return Path(relative) / "index.md"
    return Path(f"{relative}.md")


def write_reference(build: ReferenceBuild, docs_root: Path = _DEFAULT_DOCS_ROOT) -> None:
    """Replace the generated tree and remove orphaned pages."""
    if docs_root.exists():
        shutil.rmtree(docs_root)
    for route, content in build.pages.items():
        destination = docs_root / _route_path(route)
        destination.parent.mkdir(parents=True, exist_ok=True)
        destination.write_text(content)


def compare_reference(build: ReferenceBuild, docs_root: Path = _DEFAULT_DOCS_ROOT) -> list[str]:
    """Return normalized missing, stale, and extra file diagnostics."""
    expected = {_route_path(route): content for route, content in build.pages.items()}
    actual_paths = set(docs_root.rglob("*.md")) if docs_root.exists() else set()
    actual = {path.relative_to(docs_root): path.read_text() for path in actual_paths}
    diagnostics = [f"missing: {path.as_posix()}" for path in expected.keys() - actual.keys()]
    diagnostics.extend(
        f"stale: {path.as_posix()}"
        for path in expected.keys() & actual.keys()
        if expected[path] != actual[path]
    )
    diagnostics.extend(f"extra: {path.as_posix()}" for path in actual.keys() - expected.keys())
    return sorted(diagnostics)


def _compare_trees(expected_root: Path, actual_root: Path) -> list[str]:
    expected_paths = set(expected_root.rglob("*.md"))
    actual_paths = set(actual_root.rglob("*.md")) if actual_root.exists() else set()
    expected = {path.relative_to(expected_root): path.read_bytes() for path in expected_paths}
    actual = {path.relative_to(actual_root): path.read_bytes() for path in actual_paths}
    diagnostics = [f"missing: {path.as_posix()}" for path in expected.keys() - actual.keys()]
    diagnostics.extend(
        f"stale: {path.as_posix()}"
        for path in expected.keys() & actual.keys()
        if expected[path] != actual[path]
    )
    diagnostics.extend(f"extra: {path.as_posix()}" for path in actual.keys() - expected.keys())
    return sorted(diagnostics)


def _parser() -> argparse.ArgumentParser:
    parser = argparse.ArgumentParser(description=__doc__)
    action = parser.add_mutually_exclusive_group(required=True)
    action.add_argument("--write", action="store_true", help="regenerate the checked-in reference")
    action.add_argument(
        "--check", action="store_true", help="check generated parity and docstrings"
    )
    action.add_argument(
        "--inventory", type=Path, metavar="PATH", help="write normalized inventory JSON"
    )
    parser.add_argument("--package-root", type=Path, default=_DEFAULT_PACKAGE_ROOT)
    return parser


def _undocumented_parameters(obj: Any) -> list[str]:
    """Return signature parameter names a callable's docstring never describes."""

    if not callable(getattr(obj, "signature", None)):
        return []
    documented, _, _, _ = _doc_parts(obj)
    overloads = _overloads(obj)
    sources = overloads or [obj]
    names: list[str] = []
    for source in sources:
        for parameter in getattr(source, "parameters", ()):
            name = str(parameter.name)
            if name in {"self", "cls", "/", "*"} or name in names:
                continue
            if not documented.get(name):
                names.append(name)
    return names


def main(argv: Sequence[str] | None = None) -> int:
    """Run the generator CLI."""

    args = _parser().parse_args(argv)
    build = build_reference(package_root=args.package_root)
    if args.write:
        write_reference(build)
        return 0
    if args.inventory is not None:
        args.inventory.parent.mkdir(parents=True, exist_ok=True)
        args.inventory.write_text(json.dumps(build.inventory, indent=2, ensure_ascii=False) + "\n")
        return 0
    with tempfile.TemporaryDirectory(prefix="api-reference-check-") as directory:
        temporary = Path(directory)
        write_reference(build, temporary)
        diagnostics = _compare_trees(temporary, _DEFAULT_DOCS_ROOT)
    diagnostics.extend(docstring_completeness_errors(build))
    diagnostics.extend(private_surface_errors(build))
    if diagnostics:
        print("Python API reference check failed:", file=sys.stderr)
        for diagnostic in diagnostics:
            print(f"- {diagnostic}", file=sys.stderr)
        return 1
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
