#!/usr/bin/env python3
# Copyright (c) Picogrid, Inc.
# SPDX-License-Identifier: MPL-2.0

"""Regenerate dependency locks and synchronize release-policy dependency pins.

`--check` is deterministic and network-free so it can gate CI: it verifies that
every exact pin in each `.in` input appears in its committed compiled lock, that
release-policy pins match the committed manifests, and that `uv.lock` matches
`pyproject.toml`. Full lock re-resolution happens only in sync mode, because a
fresh resolve legitimately drifts whenever transitive releases appear upstream.
Direct declarations must be markerless; marker-qualified direct declarations are
rejected rather than semantically compared.
"""

from __future__ import annotations

import argparse
import json
import re
import shlex
import subprocess
import sys
import tomllib
from collections.abc import Callable, Iterable, Sequence
from pathlib import Path
from typing import NamedTuple

from packaging.requirements import InvalidRequirement, Requirement
from packaging.specifiers import InvalidSpecifier, SpecifierSet
from packaging.version import InvalidVersion, Version

REPOSITORY = Path(__file__).resolve().parents[1]
POLICY_PATH = REPOSITORY / "scripts" / "release-policy.json"
COMPILED_LOCKS = (
    REPOSITORY / "operator-app" / "requirements.txt",
    REPOSITORY / "operator-app" / "requirements-dev.txt",
    REPOSITORY / "operator-app" / "requirements-build.txt",
    REPOSITORY / "scripts" / "build-requirements.txt",
)
HEADER_PREAMBLE = "# This file was autogenerated by uv via the following command:"
HEADER_COMMAND_PREFIX = "#    "
# Options the committed headers use, plus the value-taking ones a regeneration
# might reasonably add. An option outside these sets is an error, not a guess.
COMPILE_BARE_FLAGS = frozenset({"--generate-hashes", "--universal", "--no-strip-extras"})
# `-c/--constraints` is deliberately absent: uv resolves against a constraints
# file, but nothing here inspects its declarations, so skipping it would let a
# constraint change the resolution unaudited. It is an unmodeled option until
# something reads it.
COMPILE_VALUE_FLAGS = frozenset({"-o", "--output-file", "-p", "--python"})
ROOT_REQUIREMENTS_KEY = "runtime_requirements"
DIRECT_DEPENDENCIES_KEY = "direct_runtime_dependencies"
OPERATOR_RUNTIME_KEY = "operator_runtime_requirements"
OPERATOR_OPTIONAL_KEY = "operator_optional_runtime_requirements"
REQUIREMENT_RE = re.compile(
    r"^(?P<name>[A-Za-z0-9][A-Za-z0-9._-]*)(?P<extras>\[[^]]+\])?(?P<tail>.*)$"
)
JSON_STRING_RE = re.compile(r'"(?:\\.|[^"\\])*"')
PIN_RE = re.compile(r"^([A-Za-z0-9][A-Za-z0-9._-]*)(\[[^]]+\])?==([^\s;\\]+)")
INLINE_COMMENT_RE = re.compile(r"(?:^|\s)#.*$")
# uv accepts indented options and both `--flag value` and `--flag=value` spellings,
# so every collector that walks a requirements input shares this grammar.
# The tail is captured raw, separator included. A directive must be recognized
# even when it names nothing or attaches its target, because the generic option
# branch would drop it silently and uv would then fail on input the gate had
# certified; and the separator cannot be folded away, because uv counts every
# character after it as part of the target.
INCLUDE_RE = re.compile(r"^\s*(?:-r|--requirement)(?P<tail>.*)$")
PLAIN_PATH_RE = re.compile(r"[A-Za-z0-9._][A-Za-z0-9._/-]*")
EDITABLE_RE = re.compile(r"^\s*(?:-e|--editable)(?P<tail>.*)$")


class SyncError(RuntimeError):
    """Raised when generated dependency metadata cannot be synchronized safely."""


def _relative(path: Path) -> str:
    try:
        return path.relative_to(REPOSITORY).as_posix()
    except ValueError:
        return path.as_posix()


def _normalized_name(name: str) -> str:
    return re.sub(r"[-_.]+", "-", name).lower()


def _parse_requirement(requirement: str) -> tuple[str, str, str]:
    match = REQUIREMENT_RE.fullmatch(requirement)
    if match is None:
        raise SyncError(f"cannot parse dependency requirement: {requirement!r}")
    return match.group("name"), match.group("extras") or "", match.group("tail")


def _split_marker(tail: str) -> tuple[str, str]:
    specifier, separator, marker = tail.partition(";")
    return specifier.strip(), f";{marker}" if separator else ""


def _canonical_specifier(specifier: str) -> str:
    clauses = [clause.strip() for clause in specifier.split(",") if clause.strip()]
    if not clauses or any(not clause.startswith(("<", ">", "=", "!", "~")) for clause in clauses):
        raise SyncError(f"unsupported dependency specifier: {specifier!r}")
    return ",".join(sorted(clauses))


def _project_dependencies(pyproject: Path) -> list[str]:
    with pyproject.open("rb") as stream:
        project = tomllib.load(stream)["project"]
    dependencies = project["dependencies"]
    if not isinstance(dependencies, list) or any(
        not isinstance(item, str) for item in dependencies
    ):
        raise SyncError(f"{_relative(pyproject)} project dependencies must be a list of strings")
    return dependencies


def _optional_dependency_declarations(pyproject: Path) -> list[str]:
    """Every requirement declared in a project's optional-dependency groups."""
    with pyproject.open("rb") as stream:
        groups = tomllib.load(stream)["project"].get("optional-dependencies", {})
    if not isinstance(groups, dict) or any(
        not isinstance(group, list) or any(not isinstance(item, str) for item in group)
        for group in groups.values()
    ):
        raise SyncError(
            f"{_relative(pyproject)} optional-dependencies must map to lists of strings"
        )
    return [item for group in groups.values() for item in group]


def _dependency_group_declarations(pyproject: Path) -> list[str]:
    """Requirement strings declared in PEP 735 dependency groups.

    `{include-group = "..."}` members name another group rather than a
    requirement, so they carry no marker and are inventoried through the group
    they reference.
    """
    with pyproject.open("rb") as stream:
        groups = tomllib.load(stream).get("dependency-groups", {})
    if not isinstance(groups, dict):
        raise SyncError(f"{_relative(pyproject)} dependency-groups must be a table")
    declarations: list[str] = []
    for name, members in groups.items():
        if not isinstance(members, list):
            raise SyncError(f"{_relative(pyproject)} dependency group {name!r} must be a list")
        for member in members:
            if isinstance(member, str):
                declarations.append(member)
            elif not (
                isinstance(member, dict)
                and set(member) == {"include-group"}
                and isinstance(member["include-group"], str)
            ):
                raise SyncError(
                    f"{_relative(pyproject)} dependency group {name!r} has a member that is "
                    "neither a requirement nor an include-group table"
                )
    return declarations


def _root_dependencies() -> list[str]:
    return _project_dependencies(REPOSITORY / "pyproject.toml")


def _root_project_identity() -> tuple[str, str]:
    with (REPOSITORY / "pyproject.toml").open("rb") as stream:
        project = tomllib.load(stream)["project"]
    name, version = project["name"], project["version"]
    if not isinstance(name, str) or not isinstance(version, str):
        raise SyncError("root pyproject.toml project name and version must be strings")
    return _normalized_name(name), version


def _root_project_name() -> str:
    return _root_project_identity()[0]


def _sdk_self_dependency_conflicts() -> list[str]:
    """Operator manifest declarations of the SDK that are missing or drift from the root."""
    sdk, version = _root_project_identity()
    declarations = [
        dependency
        for dependency in _project_dependencies(REPOSITORY / "operator-app" / "pyproject.toml")
        if requirement_name(dependency) == sdk
    ]
    if not declarations:
        return [f"{sdk} (operator-app/pyproject.toml does not declare the SDK dependency)"]
    conflicts: list[str] = []
    for declaration in declarations:
        pin = _exact_pin(declaration)
        if pin is None:
            conflicts.append(f"{declaration} (SDK dependency must be an exact pin)")
        elif pin.version != version:
            conflicts.append(f"{sdk}=={pin.version} (root pyproject.toml version is {version})")
        elif pin.marker or pin.extras:
            conflicts.append(
                f"{declaration} (SDK dependency must be unconditional and without extras)"
            )
    return conflicts


def _operator_direct_dependencies() -> list[str]:
    sdk = _root_project_name()
    return [
        dependency
        for dependency in _project_dependencies(REPOSITORY / "operator-app" / "pyproject.toml")
        if requirement_name(dependency) != sdk
    ]


def _operator_optional_dependencies() -> list[str]:
    with (REPOSITORY / "operator-app" / "pyproject.toml").open("rb") as stream:
        groups = tomllib.load(stream)["project"].get("optional-dependencies", {})
    if not isinstance(groups, dict) or any(
        not isinstance(group, list) or any(not isinstance(item, str) for item in group)
        for group in groups.values()
    ):
        raise SyncError(
            "operator-app/pyproject.toml optional-dependencies must map to lists of strings"
        )
    sdk = _root_project_name()
    return [
        dependency
        for group in groups.values()
        for dependency in group
        if requirement_name(dependency) != sdk
    ]


_MARKER_VARIABLES = (
    "python_full_version|python_version|os_name|sys_platform|platform_release|"
    "platform_system|platform_version|platform_machine|"
    "platform_python_implementation|implementation_name|implementation_version|extra"
)
_REVERSED_COMPARISON_RE = re.compile(
    rf"('[^']*')\s*(===|==|!=|<=|>=|<|>)\s*({_MARKER_VARIABLES})\b"
)
_FLIPPED_OPERATORS = {
    "==": "==",
    "===": "===",
    "!=": "!=",
    "<": ">",
    ">": "<",
    "<=": ">=",
    ">=": "<=",
}


def _normalize_marker(marker: str) -> str:
    """Whitespace, quote, and operand-order canonical form of a marker.

    uv canonicalizes reversed comparisons ('win32' == sys_platform) to the
    variable-first form in compiled locks, so source markers must be brought
    to the same shape or a freshly synchronized lock would never be accepted.
    """
    text = re.sub(r"\s+", " ", marker.strip()).replace('"', "'")
    return _REVERSED_COMPARISON_RE.sub(
        lambda match: f"{match.group(3)} {_FLIPPED_OPERATORS[match.group(2)]} {match.group(1)}",
        text,
    )


def _normalize_extras(extras: str | None) -> str:
    if not extras:
        return ""
    # Deduplicated: uv canonicalizes `[x,x]` and `[X,x]` to `[x]` in the lock, so
    # a repeated extra would leave the pin permanently unmatchable.
    names = sorted(
        {_normalized_name(part.strip()) for part in extras[1:-1].split(",") if part.strip()}
    )
    return f"[{','.join(names)}]"


class _Pin(NamedTuple):
    name: str
    extras: str
    version: str
    marker: str


def _exact_pin(text: str) -> _Pin | None:
    """Normalized (name, extras, version, marker) for an exact pin, else None.

    Only a single bare equality clause counts. `PIN_RE` is greedy enough to
    capture `1.0.*` or `1.0,>=1` as though they were versions, and a trailing
    clause after whitespace would simply be dropped — each would then be recorded
    as a pin no lock can ever match, leaving the staleness check permanently
    unsatisfiable. Anything else is a range, and flows to `_range_conflict()`
    where `SpecifierSet` compares it to the resolved version correctly.
    """
    match = PIN_RE.match(text)
    if not match:
        return None
    rest = text[match.end() :].strip().removesuffix("\\").strip()
    if rest and not rest.startswith(";"):
        return None
    try:
        Version(match.group(3))
    except InvalidVersion:
        return None
    marker = _normalize_marker(rest[1:]) if rest.startswith(";") else ""
    return _Pin(
        _normalized_name(match.group(1)),
        _normalize_extras(match.group(2)),
        match.group(3),
        marker,
    )


def _pins_from_lines(lines: Iterable[str]) -> dict[str, set[tuple[str, str, str]]]:
    """Exact pins per normalized name as (extras, version, normalized marker) tuples."""
    pins: dict[str, set[tuple[str, str, str]]] = {}
    for line in lines:
        pin = _exact_pin(line)
        if pin is not None:
            pins.setdefault(pin.name, set()).add((pin.extras, pin.version, pin.marker))
    return pins


def _pin_key(entry: tuple[str, str, str]) -> tuple[str, Version | str, str]:
    """Comparison key for a pin tuple, with the version compared per PEP 440.

    uv writes a distribution's metadata version into the lock, which need not
    match the spelling in the input: `v1.0`, `01.0`, and `1.0.0` all resolve to a
    lock entry reading `1.0`. Comparing raw text would leave such a pin
    permanently stale — sync succeeds, and the check right after it fails.
    `Version` equality is hash-consistent, so these keys work in a set; the raw
    text is kept in the tuples themselves for diagnostics and policy output,
    which must reproduce the committed files byte for byte.
    """
    extras, version, marker = entry
    try:
        return (extras, Version(version), marker)
    except InvalidVersion:
        return (extras, version, marker)


def _pin_keys(entries: Iterable[tuple[str, str, str]]) -> set[tuple[str, Version | str, str]]:
    return {_pin_key(entry) for entry in entries}


def _pinned_requirement_sets(requirements_path: Path) -> dict[str, set[tuple[str, str, str]]]:
    """Exact pins in a compiled lock, read as physical lines.

    Locks use backslash continuations for their hash blocks, so they must not be
    joined the way a requirements input is.
    """
    return _pins_from_lines(requirements_path.read_text(encoding="utf-8").splitlines())


def _pinned_version_sets(requirements_path: Path) -> dict[str, set[str]]:
    return {
        name: {version for _extras, version, _marker in entries}
        for name, entries in _pinned_requirement_sets(requirements_path).items()
    }


def canonical_root_requirement(dependency: str) -> str:
    """Policy-canonical form of a root pyproject dependency string."""
    name, extras, tail = _parse_requirement(dependency)
    specifier, marker = _split_marker(tail)
    return f"{name}{extras}{_canonical_specifier(specifier)}{marker}"


def requirement_name(dependency: str) -> str:
    """Normalized distribution name of a dependency string."""
    return _normalized_name(_parse_requirement(dependency)[0])


def _sync_operator_requirement(requirement: str, versions: dict[str, set[str]]) -> str:
    name, extras, tail = _parse_requirement(requirement)
    match = re.match(r"^==[^\s;]+(?P<rest>.*)$", tail)
    if match is None:
        raise SyncError(f"operator policy dependency must use an exact pin: {requirement!r}")
    found = versions.get(_normalized_name(name))
    if not found:
        raise SyncError(
            f"operator policy dependency {name!r} is absent from operator-app/requirements.txt"
        )
    if len(found) != 1:
        raise SyncError(
            f"operator policy dependency {name!r} has ambiguous resolved versions: {sorted(found)}"
        )
    return f"{name}{extras}=={next(iter(found))}{match.group('rest')}"


def _array_span(text: str, key: str) -> tuple[int, int] | None:
    match = re.search(rf'"{re.escape(key)}"\s*:\s*\[', text)
    if match is None:
        return None
    start = text.find("[", match.start())
    in_string = False
    escaped = False
    depth = 0
    for index in range(start, len(text)):
        character = text[index]
        if in_string:
            if escaped:
                escaped = False
            elif character == "\\":
                escaped = True
            elif character == '"':
                in_string = False
            continue
        if character == '"':
            in_string = True
        elif character == "[":
            depth += 1
        elif character == "]":
            depth -= 1
            if depth == 0:
                return start, index + 1
    raise SyncError(f"unterminated release-policy array: {key}")


def _rewrite_policy_array(
    text: str,
    key: str,
    rewrite: Callable[[str], str],
) -> str:
    span = _array_span(text, key)
    if span is None:
        return text
    start, end = span
    array_text = text[start:end]
    values = json.loads(array_text)
    if not isinstance(values, list) or any(not isinstance(value, str) for value in values):
        raise SyncError(f"release-policy key {key!r} must be a list of strings")
    replacements = iter(rewrite(value) for value in values)
    rewritten = JSON_STRING_RE.sub(lambda _match: json.dumps(next(replacements)), array_text)
    return text[:start] + rewritten + text[end:]


def _replace_policy_array(text: str, key: str, values: list[str]) -> str:
    span = _array_span(text, key)
    if span is None:
        raise SyncError(f"release policy is missing the {key!r} array")
    start, end = span
    array_text = text[start:end]
    indent_match = re.search(r"\n(\s*)\"", array_text)
    close_match = re.search(r"\n(\s*)\]$", array_text)
    indent = indent_match.group(1) if indent_match else "    "
    closing = close_match.group(1) if close_match else "  "
    body = ",\n".join(f"{indent}{json.dumps(value)}" for value in values)
    rebuilt = f"[\n{body}\n{closing}]" if values else "[]"
    return text[:start] + rebuilt + text[end:]


def _require_reviewed_dependency_set(text: str, root_dependencies: Sequence[str]) -> None:
    declared = {requirement_name(dependency) for dependency in root_dependencies}
    try:
        entries = json.loads(text)[DIRECT_DEPENDENCIES_KEY]
    except (json.JSONDecodeError, KeyError, TypeError) as error:
        raise SyncError(
            f"release policy is missing the {DIRECT_DEPENDENCIES_KEY!r} review entries"
        ) from error
    if not isinstance(entries, dict) or any(not isinstance(name, str) for name in entries):
        raise SyncError(
            f"release-policy key {DIRECT_DEPENDENCIES_KEY!r} must be keyed by dependency name"
        )
    reviewed = set(entries)
    if declared != reviewed:
        added = ", ".join(sorted(declared - reviewed)) or "none"
        removed = ", ".join(sorted(reviewed - declared)) or "none"
        raise SyncError(
            f"root dependency set changed (added: {added}; removed: {removed}); update "
            f"{DIRECT_DEPENDENCIES_KEY} and the dependency review entries in "
            "scripts/release-policy.json before synchronizing"
        )


def _describe_locked(found: set[tuple[str, str, str]]) -> str:
    entries = sorted(
        f"{extras}{version}; {marker}" if marker else f"{extras}{version}"
        for extras, version, marker in found
    )
    return ", ".join(entries) or "absent"


def _manifest_pin_conflicts(declarations: Sequence[str], lock_path: Path) -> list[str]:
    locked = _pinned_requirement_sets(lock_path)
    conflicts: list[str] = []
    for dependency in declarations:
        pin = _exact_pin(dependency)
        if pin is None:
            conflicts.append(f"{dependency!r} (operator declarations must use exact pins)")
            continue
        found = locked.get(pin.name, set())
        if _pin_key((pin.extras, pin.version, pin.marker)) not in _pin_keys(found):
            declared = f"{pin.name}{pin.extras}=={pin.version}"
            if pin.marker:
                declared = f"{declared}; {pin.marker}"
            conflicts.append(f"{declared} ({_relative(lock_path)} has: {_describe_locked(found)})")
    return conflicts


def _build_system_requires(pyproject: Path) -> list[str]:
    with pyproject.open("rb") as stream:
        requires = tomllib.load(stream)["build-system"]["requires"]
    if not isinstance(requires, list) or any(not isinstance(item, str) for item in requires):
        raise SyncError(f"{_relative(pyproject)} build-system requires must be a list of strings")
    return requires


def _extras_names(normalized_extras: str) -> frozenset[str]:
    return frozenset(normalized_extras[1:-1].split(",")) if normalized_extras else frozenset()


def _range_conflict(
    dependency: str, locked: dict[str, set[tuple[str, str, str]]], lock_path: Path
) -> str | None:
    """Conflict text when a ranged declaration is not satisfied by the lock.

    An unmarked declaration applies to every environment, so every locked
    branch of the name must satisfy it. A marker-qualified declaration governs
    only branches with the same normalized marker plus unmarked branches;
    disjoint-marker branches are outside its applicability. Declared extras
    must be retained by every applicable branch, or the extra-selected
    dependency closure would be absent from the compiled environment.
    """
    name, extras, tail = _parse_requirement(dependency)
    specifier_text, marker = _split_marker(tail)
    declared_marker = _normalize_marker(marker[1:]) if marker else ""
    declared_extras = _extras_names(_normalize_extras(extras))
    found = locked.get(_normalized_name(name), set())
    if not found:
        return f"{dependency!r} (absent from {_relative(lock_path)})"
    applicable = {
        entry for entry in found if not declared_marker or entry[2] in ("", declared_marker)
    }
    if not applicable:
        return f"{dependency!r} (no applicable locked entry in {_relative(lock_path)})"
    try:
        specifier = SpecifierSet(specifier_text)
        if all(
            specifier.contains(Version(version), prereleases=True)
            and declared_extras <= _extras_names(entry_extras)
            for entry_extras, version, _entry_marker in applicable
        ):
            return None
    except (InvalidSpecifier, InvalidVersion) as error:
        raise SyncError(f"cannot evaluate dependency specifier {dependency!r}: {error}") from error
    return f"{dependency!r} ({_relative(lock_path)} has: {_describe_locked(applicable)})"


def _build_requirement_conflicts(declarations: Sequence[str], lock_path: Path) -> list[str]:
    """Build-system declarations the compiled build lock does not satisfy.

    Exact pins must match a locked entry; ranged declarations must be satisfied
    by at least one locked version of the same name.
    """
    locked = _pinned_requirement_sets(lock_path)
    conflicts: list[str] = []
    for dependency in declarations:
        pin = _exact_pin(dependency)
        if pin is None:
            conflict = _range_conflict(dependency, locked, lock_path)
            if conflict is not None:
                conflicts.append(conflict)
        elif _pin_key((pin.extras, pin.version, pin.marker)) not in _pin_keys(
            locked.get(pin.name, set())
        ):
            conflicts.append(
                f"{pin.name}{pin.extras}=={pin.version} "
                f"({_relative(lock_path)} has: {_describe_locked(locked.get(pin.name, set()))})"
            )
    return conflicts


def _shared_pin_conflicts(declarations: Sequence[str], lock_path: Path) -> list[str]:
    """Declarations that disagree with a lock which resolves the same name.

    Names the lock does not contain are skipped (the lock need not consume every
    declaration). Exact pins must match a locked entry; ranged declarations must
    be satisfied by at least one locked version.
    """
    locked = _pinned_requirement_sets(lock_path)
    conflicts: list[str] = []
    for dependency in declarations:
        pin = _exact_pin(dependency)
        if pin is None:
            if requirement_name(dependency) not in locked:
                continue
            conflict = _range_conflict(dependency, locked, lock_path)
            if conflict is not None:
                conflicts.append(conflict)
        elif pin.name in locked and _pin_key(
            (pin.extras, pin.version, pin.marker)
        ) not in _pin_keys(locked[pin.name]):
            conflicts.append(
                f"{pin.name}{pin.extras}=={pin.version} "
                f"({_relative(lock_path)} has: {_describe_locked(locked[pin.name])})"
            )
    return conflicts


def _operator_manifest_pin_conflicts() -> list[str]:
    """Manifest declarations that the compiled locks or root project do not satisfy."""
    return (
        _sdk_self_dependency_conflicts()
        + _manifest_pin_conflicts(
            _operator_direct_dependencies(),
            REPOSITORY / "operator-app" / "requirements.txt",
        )
        + _manifest_pin_conflicts(
            _operator_optional_dependencies(),
            REPOSITORY / "operator-app" / "requirements-dev.txt",
        )
        + _build_requirement_conflicts(
            _build_system_requires(REPOSITORY / "pyproject.toml"),
            REPOSITORY / "scripts" / "build-requirements.txt",
        )
        + _build_requirement_conflicts(
            _build_system_requires(REPOSITORY / "operator-app" / "pyproject.toml"),
            REPOSITORY / "operator-app" / "requirements-build.txt",
        )
        + _shared_pin_conflicts(
            _root_dependencies(),
            REPOSITORY / "operator-app" / "requirements.txt",
        )
    )


def _synchronized_policy_text(
    text: str,
    root_dependencies: Sequence[str],
    operator_versions: dict[str, set[str]],
    operator_dependencies: Sequence[str],
) -> str:
    _require_reviewed_dependency_set(text, root_dependencies)
    text = _replace_policy_array(
        text,
        ROOT_REQUIREMENTS_KEY,
        sorted(canonical_root_requirement(dependency) for dependency in root_dependencies),
    )
    text = _replace_policy_array(
        text,
        OPERATOR_RUNTIME_KEY,
        sorted(canonical_root_requirement(dependency) for dependency in operator_dependencies),
    )
    text = _rewrite_policy_array(
        text,
        OPERATOR_OPTIONAL_KEY,
        lambda requirement: _sync_operator_requirement(requirement, operator_versions),
    )
    return text


def _synchronized_policy(operator_requirements: Path) -> str:
    return _synchronized_policy_text(
        POLICY_PATH.read_text(encoding="utf-8"),
        _root_dependencies(),
        _pinned_version_sets(operator_requirements),
        _operator_direct_dependencies(),
    )


def _header_command(lock_path: Path) -> tuple[list[str], Path]:
    lines = lock_path.read_text(encoding="utf-8").splitlines()
    if (
        len(lines) < 2
        or lines[0] != HEADER_PREAMBLE
        or not lines[1].startswith(HEADER_COMMAND_PREFIX)
    ):
        raise SyncError(f"{_relative(lock_path)} has no recognized uv compile command header")
    command = shlex.split(lines[1][len(HEADER_COMMAND_PREFIX) :])
    if command[:3] != ["uv", "pip", "compile"]:
        raise SyncError(f"{_relative(lock_path)} header is not a uv pip compile command")
    try:
        output_index = command.index("-o") + 1
    except ValueError:
        try:
            output_index = command.index("--output-file") + 1
        except ValueError as error:
            raise SyncError(f"{_relative(lock_path)} header has no output path") from error
    output = Path(command[output_index])
    candidates = (lock_path.parent, REPOSITORY)
    matching = [cwd for cwd in candidates if (cwd / output).resolve() == lock_path.resolve()]
    if not matching:
        raise SyncError(f"{_relative(lock_path)} header output does not resolve to that lock")
    cwd = matching[0]
    return command, cwd


def _source_inputs(command: list[str], cwd: Path) -> list[Path]:
    """Requirements inputs a lock header compiles from.

    Held to the same contract as a nested `-r` target: inside the compile
    directory and a regular file. `_header_command()` validates only the output
    path, so without this a lock header could point the gate at a device node or
    outside the checkout before `_include_target()` ever runs.

    Only `.in` inputs are accepted, and only modelled options. `uv pip compile`
    also reads `pyproject.toml`, `setup.py`, and `setup.cfg`, which these
    collectors would misread as requirements text; and an unmodelled
    value-taking option such as `--override overrides.txt` would leave its value
    looking like an input. Both are rejected rather than guessed at, so adding
    an option to a header is a deliberate change here.
    """
    inputs: list[Path] = []
    skip = False
    root = cwd.resolve()
    for argument in command[3:]:
        if skip:
            skip = False
        elif argument.startswith("-"):
            flag = argument.split("=", 1)[0]
            if flag in COMPILE_VALUE_FLAGS:
                skip = "=" not in argument
            elif flag not in COMPILE_BARE_FLAGS:
                raise SyncError(f"unmodeled uv compile option in header: {argument!r}")
        else:
            if not argument.endswith(".in"):
                raise SyncError(f"compile input is not a requirements file: {argument!r}")
            resolved = (root / argument).resolve()
            if not resolved.is_relative_to(root):
                raise SyncError(f"compile input escapes {_relative(root)}: {argument!r}")
            if not resolved.is_file():
                raise SyncError(f"compile input is not a regular file: {argument!r}")
            inputs.append(resolved)
    if not inputs:
        raise SyncError(f"uv compile command has no input files: {shlex.join(command)}")
    return inputs


def _compile(lock_path: Path) -> None:
    command, cwd = _header_command(lock_path)
    result = subprocess.run(
        command,
        cwd=cwd,
        check=False,
        text=True,
        stdout=subprocess.PIPE,
        stderr=subprocess.STDOUT,
    )
    if result.returncode != 0:
        if result.stdout:
            print(result.stdout, file=sys.stderr, end="" if result.stdout.endswith("\n") else "\n")
        raise SyncError(f"uv compile failed for {_relative(lock_path)}")


def _source_pin_sets(
    source: Path, visited: set[Path] | None = None, root: Path | None = None
) -> dict[str, set[tuple[str, str, str]]]:
    """Exact pins declared in an input file, following nested `-r` includes.

    Read as logical lines: a wrapped pin such as `foo==\\` + `1.0` is one pin to
    uv, and missing it here would leave the name looking range-only, so
    `_stale_lock_pins()` would accept any locked version for it.
    """
    visited = visited if visited is not None else set()
    if source in visited:
        return {}
    visited.add(source)
    root = root if root is not None else source.parent.resolve()
    lines = _requirement_lines(source.read_text(encoding="utf-8"))
    pins = _pins_from_lines(lines)
    for line in lines:
        included = _include_target(line, source, root)
        if included is not None:
            nested = _source_pin_sets(included, visited, root)
            for name, entries in nested.items():
                pins.setdefault(name, set()).update(entries)
    return pins


def _requirement_lines(text: str) -> list[str]:
    """Comment-stripped lines of a requirements input.

    uv accepts no backslash continuation anywhere in a requirements input —
    verified against `uv pip compile`, which rejects one splitting a marker, an
    operator, a version, or an include path, and rejects a dangling one too. So a
    trailing backslash is refused rather than joined: joining would assemble a
    declaration uv never sees and certify a source it cannot compile.

    Inline comments start at an unescaped `#` at line start or after whitespace,
    and are removed first, so a comment ending in a backslash is a comment rather
    than a continuation. Compiled locks are unaffected — they are read as physical
    lines, where the continuation carries hash blocks.
    """
    lines = [INLINE_COMMENT_RE.sub("", physical) for physical in text.splitlines()]
    for line in lines:
        if line.endswith("\\"):
            raise SyncError(f"requirements input has a line continuation: {line.strip()!r}")
    return lines


def _include_target(line: str, source: Path, root: Path) -> Path | None:
    """The nested requirements file a `-r`/`--requirement` line names, else None.

    The target must be a plain relative path. uv's own reading of this value is
    a small language — it strips quotes anywhere, honours backslash escapes
    outside them, cuts at `#`, and expands `${VAR}` — and every one of those
    rules is a way for the gate to open a different file than uv compiles.
    Rather than reimplement that language and stay bug-for-bug aligned with it,
    anything outside `[A-Za-z0-9._/-]` is refused with an actionable message.
    Every committed include is already a plain path, and one that is not should
    be a deliberate, reviewed change here.

    The target must then resolve inside `root` and be a regular file. `root` is
    the top-level input's directory and stays fixed through the recursion, so
    `sub/outer.in` may include `../common.in` while `-r /dev/zero` or a path
    outside the tree — either of which could hang or exhaust the gate — is
    refused before it is opened.
    """
    match = INCLUDE_RE.match(line)
    if match is None:
        return None
    directive = line.strip()
    tail = match.group("tail")
    if tail and tail[0] not in " \t=":
        raise SyncError(f"requirements include needs a separator: {directive!r}")
    name = tail.removeprefix("=").strip()
    if not name:
        raise SyncError(f"requirements include names no file: {directive!r}")
    if not PLAIN_PATH_RE.fullmatch(name):
        raise SyncError(f"requirements include must be a plain relative path: {directive!r}")
    target = (source.parent / name).resolve()
    if not target.is_relative_to(root):
        raise SyncError(f"requirements include escapes {_relative(root)}: {directive!r}")
    if not target.is_file():
        raise SyncError(f"requirements include is not a regular file: {directive!r}")
    return target


def _source_declarations(
    source: Path, visited: set[Path] | None = None, root: Path | None = None
) -> list[tuple[Path, str]]:
    """(file, declaration) for every requirement declared in an input, following `-r` includes."""
    visited = visited if visited is not None else set()
    if source in visited:
        return []
    visited.add(source)
    root = root if root is not None else source.parent.resolve()
    declarations: list[tuple[Path, str]] = []
    for line in _requirement_lines(source.read_text(encoding="utf-8")):
        included = _include_target(line, source, root)
        if included is not None:
            declarations.extend(_source_declarations(included, visited, root))
            continue
        if EDITABLE_RE.match(line):
            # An editable is never comparable to a compiled lock, whatever its
            # target parses as, so reject the line rather than its target.
            declarations.append((source, line.strip()))
            continue
        stripped = line.strip()
        if not stripped:
            continue
        if stripped.startswith("-"):
            # Held to the same standard as a lock header: an option that changes
            # what uv resolves — `--override`, `--index-url` — must not be
            # silently dropped, or the gate audits a different input set.
            raise SyncError(f"unmodeled option in {_relative(source)}: {stripped!r}")
        declarations.append((source, stripped))
    return declarations


def _source_declared_names(source: Path, root: Path | None = None) -> set[str]:
    """Every requirement name declared in an input file, following `-r` includes."""
    return {
        requirement_name(text)
        for _path, text in _source_declarations(source, None, root)
        if REQUIREMENT_RE.fullmatch(text) is not None
    }


def _exact_version(requirement: Requirement) -> str | None:
    """The single exact version a requirement pins, or None when it is a range.

    Wildcard equality is a range here too, matching `_exact_pin()`: the two must
    agree, or the cross-check below would flag every wildcard declaration.
    """
    clauses = list(requirement.specifier)
    if len(clauses) != 1 or clauses[0].operator not in ("==", "==="):
        return None
    version = clauses[0].version
    return None if "*" in version else version


def _parsers_agree(declaration: str, requirement: Requirement) -> bool:
    """True when the regex parser reads a declaration the same way `packaging` does.

    `_range_conflict()` re-reads the raw text with `_parse_requirement()`, so a
    spelling the two disagree about — `demo [x]>=1`, `demo(>=1)` — is compared to
    the lock with the wrong extras or specifier, or crashes there. Requiring the
    two to agree keeps one contract instead of two.
    """
    try:
        name, extras, tail = _parse_requirement(declaration)
        specifier = SpecifierSet(_split_marker(tail)[0])
    except (SyncError, InvalidSpecifier):
        return False
    return (
        _normalized_name(name) == _normalized_name(requirement.name)
        and _extras_names(_normalize_extras(extras))
        == {_normalized_name(extra) for extra in requirement.extras}
        and specifier == requirement.specifier
    )


def _declaration_conflicts(manifest: Path, declarations: Iterable[str]) -> list[str]:
    """Declarations in one manifest the deterministic lock checker cannot validate.

    Five fail-closed rules, all the same idea: the checker rejects what it cannot
    compare to a lock. A declaration must parse as a PEP 508 requirement, because
    every downstream comparison matches parsed names, extras, and versions, and
    the regex parser that replays it downstream must read it identically. It must
    not be a direct reference, because `_source_pin_sets()` records only `==`
    pins, so a URL or revision change would slip through `_stale_lock_pins()` as
    resolver-chosen. An exact pin must be spelled the way that same pin parser
    reads it, or it is silently demoted to a range and any locked version passes.
    And it must carry no environment marker: the marker field is read, never
    evaluated, so a direct reference URL containing a semicolon
    (`demo @ file:///tmp/demo;v1`) is classified by what it is rather than
    mistaken for a marker.
    """
    conflicts: list[str] = []
    for declaration in declarations:
        try:
            requirement = Requirement(declaration)
        except InvalidRequirement:
            conflicts.append(
                f"{_relative(manifest)}: {declaration!r} "
                "(not a PEP 508 requirement the lock checker can parse)"
            )
            continue
        name = _normalized_name(requirement.name)
        exact = _exact_version(requirement)
        pin = _exact_pin(declaration)
        if requirement.url is not None:
            conflicts.append(
                f"{_relative(manifest)}: {name} ({declaration!r}) "
                "(direct references are not comparable to a compiled lock)"
            )
        elif not _parsers_agree(declaration, requirement):
            conflicts.append(
                f"{_relative(manifest)}: {name} ({declaration!r}) "
                "(spell the requirement as `name[extras]specifier`, without spaces)"
            )
        elif exact is not None and (pin is None or pin.version != exact):
            conflicts.append(
                f"{_relative(manifest)}: {name} ({declaration!r}) "
                "(spell an exact pin as `name==version`, without spaces)"
            )
        elif requirement.marker is not None:
            conflicts.append(
                f"{_relative(manifest)}: {name} ({declaration!r}) "
                "(environment markers are not compared against a compiled lock)"
            )
    return conflicts


def _direct_declarations() -> dict[Path, list[str]]:
    """Every direct dependency declaration in the repository, keyed by manifest.

    Compiled locks and `uv.lock` are excluded: uv generates them and its marker
    forks are legitimate. Everything a human edits is inventoried here, so a new
    declaration surface must be added to this function to be governed.
    """
    declarations: dict[Path, list[str]] = {}
    for lock_path in COMPILED_LOCKS:
        command, cwd = _header_command(lock_path)
        for source in _source_inputs(command, cwd):
            for manifest, declaration in _source_declarations(source, None, cwd.resolve()):
                declarations.setdefault(manifest, []).append(declaration)

    manifests = (REPOSITORY / "pyproject.toml", REPOSITORY / "operator-app" / "pyproject.toml")
    for manifest in manifests:
        declarations[manifest] = (
            _project_dependencies(manifest)
            + _optional_dependency_declarations(manifest)
            + _build_system_requires(manifest)
            + _dependency_group_declarations(manifest)
        )
    return declarations


def _unsupported_declarations() -> list[str]:
    """Every direct declaration the deterministic lock checker will not certify.

    uv may rename marker variables, fold clauses against its resolution floor, drop
    always-true clauses, or elide always-false entries. Proving source and lock markers
    select the same environments requires PEP 508 semantics this checker deliberately
    omits, so it rejects declarations rather than certifying locks it cannot verify.
    """
    return sorted(
        {
            conflict
            for manifest, declarations in _direct_declarations().items()
            for conflict in _declaration_conflicts(manifest, declarations)
        }
    )


def _direct_lock_entries(lock_path: Path) -> dict[str, set[tuple[str, str, str]]]:
    """Locked entries annotated as coming directly from a `-r` input."""
    entries: dict[str, set[tuple[str, str, str]]] = {}
    current: _Pin | None = None
    for line in lock_path.read_text(encoding="utf-8").splitlines():
        pin = _exact_pin(line)
        if pin is not None:
            current = pin
            continue
        body = line.strip()
        if not body.startswith("#"):
            continue
        body = body.lstrip("#").strip()
        if body.startswith("via"):
            body = body[3:].strip()
        if body.startswith(("-r ", "--requirement ")) and current is not None:
            entries.setdefault(current.name, set()).add(
                (current.extras, current.version, current.marker)
            )
    return entries


def _stale_lock_pins(lock_path: Path) -> bool:
    """True when the input `.in` files disagree with the compiled lock.

    Every source pin requires a locked entry with the same extras, version, and
    normalized marker; and every locked entry annotated as a direct `-r` input
    must match a surviving source pin tuple (or belong to a name the sources
    declare only as a range), so removing a pin — or one marker-disjoint branch
    of a pin — marks the retained lock stale instead of shipping it.

    A ranged source declaration has no pin tuple to compare, so the resolved
    version is checked against its specifier instead. Without that, narrowing an
    input to a range the committed lock no longer satisfies would be waved
    through as resolver-chosen.
    """
    command, cwd = _header_command(lock_path)
    locked = _pinned_requirement_sets(lock_path)
    declared_names: set[str] = set()
    source_pins: dict[str, set[tuple[str, str, str]]] = {}
    for source in _source_inputs(command, cwd):
        declared_names |= _source_declared_names(source, cwd.resolve())
        for _path, declaration in _source_declarations(source, None, cwd.resolve()):
            if (
                _exact_pin(declaration) is None
                and REQUIREMENT_RE.fullmatch(declaration)
                and _range_conflict(declaration, locked, lock_path) is not None
            ):
                return True
        for name, entries in _source_pin_sets(source, None, cwd.resolve()).items():
            source_pins.setdefault(name, set()).update(entries)
            found = locked.get(name, set())
            for entry in entries:
                if _pin_key(entry) not in _pin_keys(found):
                    return True
    for name, direct_entries in _direct_lock_entries(lock_path).items():
        if name not in declared_names:
            return True
        pinned = source_pins.get(name)
        if pinned is None:
            continue  # declared only as a range; validated against its specifier above
        if not _pin_keys(direct_entries) <= _pin_keys(pinned):
            return True
    return False


def _report_unsupported_declarations(conflicts: Sequence[str]) -> None:
    """Print the fail-closed declaration diagnostic to stderr."""
    print(
        "The deterministic lock checker validates only markerless PEP 508 direct "
        "dependency declarations, and rejects these:",
        file=sys.stderr,
    )
    for conflict in conflicts:
        print(f"  - {conflict}", file=sys.stderr)
    print(
        "Express the dependency as a markerless requirement and run `make sync-deps`, "
        "or add reviewed checker support to scripts/sync_dep_locks.py before "
        "introducing this declaration.",
        file=sys.stderr,
    )


def _report_manifest_conflicts(conflicts: Sequence[str]) -> None:
    print("Manifest declarations are not satisfied by the compiled locks:", file=sys.stderr)
    for conflict in conflicts:
        print(f"  - {conflict}", file=sys.stderr)
    print(
        "Align the pyproject manifests (dependencies and build-system requires) with "
        "their requirements inputs, then run `make sync-deps`.",
        file=sys.stderr,
    )


def _check() -> int:
    unsupported = _unsupported_declarations()
    if unsupported:
        _report_unsupported_declarations(unsupported)
        return 1
    stale: list[str] = []
    for lock_path in COMPILED_LOCKS:
        if _stale_lock_pins(lock_path):
            stale.append(_relative(lock_path))

    policy = _synchronized_policy(REPOSITORY / "operator-app" / "requirements.txt")
    if policy != POLICY_PATH.read_text(encoding="utf-8"):
        stale.append(_relative(POLICY_PATH))

    lock_check = subprocess.run(
        ["uv", "lock", "--check"],
        cwd=REPOSITORY,
        text=True,
        stdout=subprocess.PIPE,
        check=False,
        stderr=subprocess.STDOUT,
    )
    if lock_check.returncode != 0:
        stale.append("uv.lock")

    conflicts = _operator_manifest_pin_conflicts()
    if conflicts:
        _report_manifest_conflicts(conflicts)
    if stale:
        print("Dependency lock consistency check failed.", file=sys.stderr)
        print("Stale generated files:", file=sys.stderr)
        for path in stale:
            print(f"  - {path}", file=sys.stderr)
        print(
            "Run `make sync-deps`, review the policy diff, and commit the results.", file=sys.stderr
        )
    if stale or conflicts:
        return 1
    print("Dependency locks and release policy are consistent.")
    return 0


def _sync() -> int:
    unsupported = _unsupported_declarations()
    if unsupported:
        _report_unsupported_declarations(unsupported)
        raise SyncError("unsupported direct dependency declarations")
    for lock_path in COMPILED_LOCKS:
        _compile(lock_path)
    subprocess.run(["uv", "lock"], cwd=REPOSITORY, check=True)
    conflicts = _operator_manifest_pin_conflicts()
    if conflicts:
        _report_manifest_conflicts(conflicts)
        raise SyncError("operator manifest pins disagree with the compiled lock")
    policy = _synchronized_policy(REPOSITORY / "operator-app" / "requirements.txt")
    POLICY_PATH.write_text(policy, encoding="utf-8")
    print("Dependency locks and release policy synchronized.")
    return 0


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument(
        "--check",
        action="store_true",
        help="verify committed locks and policy pins deterministically without modifying them",
    )
    arguments = parser.parse_args()
    try:
        return _check() if arguments.check else _sync()
    except (OSError, KeyError, subprocess.CalledProcessError, SyncError) as error:
        print(f"dependency synchronization failed: {error}", file=sys.stderr)
        return 2


if __name__ == "__main__":
    raise SystemExit(main())
